### ISSUE TITLE
[ overlay_tutorial: 0.2.1 ] overlay not shown properly inside the widget

### ISSUE THREAD

**Issue by dwikyhardi** [TabooSun/overlay_tutorial#12]
hi, i got some problem in my apps. i use your lib to show overlay tutorial in my apps, but something seems wrong. i don't understand where i'm wrong. the hole in that shown in my apps is far below the widget it's self. i'm using your library as my parent widget as in the **README** and the child is **Scaffold**, inside the **Scaffold** is **SingleChildScrollView** and a **Column** and there is some **Stack** widget as well. layout that contains **OverlayTutorial** is inside a **IndexedStack** **(BottomAppBar)**

**Comment by dwikyhardi** [comment]
@TabooSun can you help me with this?

**Comment by TabooSun** [comment]
Can you provide a minimal producible code?

**Comment by dwikyhardi** [comment]
@TabooSun , you can clone from this repo [repo](https://github.com/dwikyhardi/test_overlay)

**Comment by dwikyhardi** [comment]
Btw, my device is Samsung A71

> @TabooSun , you can clone from this repo [repo](https://github.com/dwikyhardi/test_overlay)

**Comment by TabooSun** [comment]
The package has been updated. I have tried migrating your code to the latest version, it should be working now. If it is not, reopen this issue.
