### ISSUE TITLE
Question: Disable background widget interaction 

### ISSUE THREAD

**Issue by hashirshoaeb** [TabooSun/overlay_tutorial#18]
How to disable the user interaction beneath the overlay, when the OverLay scope is enabled?

**Comment by TabooSun** [comment]
You should be able to do so with `AbsorbPointer`.  Check https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html

**Comment by hashirshoaeb** [comment]
Thank you for your quick response. `AbsorbPointer` fulfils my need. I would recommend you to add this feature in your package as well. 

Have a great day. 🙂
