### ISSUE TITLE
[BREAKING] OverlayTutorialWidgetHint is rebuilt too frequently

### ISSUE THREAD

**Issue by ilkercankaya** [TabooSun/overlay_tutorial#23]
Great library, it makes highlighting stuff very easy. Thank you a lot. 

However, there is a big issue I noticed. The builder for `OverlayTutorialWidgetHint` is called too frequently. What I mean is I think it is called every frame.

To prove this just add a print statement to the build method.

[For example here,](https://github.com/TabooSun/overlay_tutorial/blob/master/example/lib/main.dart) add `print("IAMREBUILT")` to line 156  and you will see that the widget gets rebuilt very frequently. This also has the following problem. I have a `skip`button in my highlights and when pressed I turns every highlight off by switching `OverlayTutorialScope` to a `SizedBox.shrink()` but `OverlayTutorialWidgetHint` throws an exception saying:

> `
> I/flutter ( 8700): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
> I/flutter ( 8700): The following assertion was thrown during a scheduler callback:
> I/flutter ( 8700): setState() called after dispose(): _OverlayTutorialScopeState#eff5b(lifecycle state: defunct, not
> I/flutter ( 8700): mounted)
> I/flutter ( 8700): This error happens if you call setState() on a State object for a widget that no longer appears in
> I/flutter ( 8700): the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error
> I/flutter ( 8700): can occur when code calls setState() from a timer or an animation callback.
> I/flutter ( 8700): The preferred solution is to cancel the timer or stop listening to the animation in the dispose()
> I/flutter ( 8700): callback. Another solution is to check the "mounted" property of this object before calling
> I/flutter ( 8700): setState() to ensure the object is still in the tree.
> I/flutter ( 8700): This error might indicate a memory leak if setState() is being called because another object is
> I/flutter ( 8700): retaining a reference to this State object after it has been removed from the tree. To avoid memory
> I/flutter ( 8700): leaks, consider breaking the reference to this object during dispose().
> 
> I/flutter ( 8700): #2      _OverlayTutorialScopeState.updateChildren
> package:overlay_tutorial/…/widgets/overlay_tutorial_scope.dart:43
> I/flutter ( 8700): #3      _OverlayTutorialHoleState.deactivate.<anonymous closure>
> package:overlay_tutorial/…/widgets/overlay_tutorial_hole.dart:70
> `

Is there a way to fix this? I am really enjoying the library and I want to use it but this bug is a breaking bug for me.

**Comment by TabooSun** [comment]
This is fixed in 2.0.4.

Reopen this issue if the issue persists.

Cheers!

**Comment by ilkercankaya** [comment]
I tried with 2.0.4 but sadly the issue persists,

Here is a full example, use this widget somewhere and you will see the console spam `I_AM_REBUILT`. due to line 100.

```
class TutorialOverlay extends StatefulWidget {
  const TutorialOverlay({Key key}) : super(key: key);

  @override
  _TutorialOverlayState createState() => _TutorialOverlayState();
}

class _TutorialOverlayState extends State<TutorialOverlay>
    with SingleTickerProviderStateMixin {
  AnimationController _animationController;
  Animation<Offset> _tweenAnimation;

  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      duration: const Duration(milliseconds: 300),
      vsync: this,
    );
  }

  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;
    final tutorialColor = Colors.yellow;
    return OverlayTutorialScope(
      enabled: true,
      overlayColor: Colors.blueAccent.withOpacity(.6),
      child: SafeArea(
        child: Scaffold(
          appBar: AppBar(),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const SizedBox(height: 64),
                Text(
                  'You have pushed the button this many times:',
                ),
                OverlayTutorialHole(
                  enabled: true,
                  overlayTutorialEntry: OverlayTutorialRectEntry(
                    padding: const EdgeInsets.symmetric(horizontal: 8.0),
                    radius: const Radius.circular(16.0),
                    overlayTutorialHints: <OverlayTutorialWidgetHint>[
                      OverlayTutorialWidgetHint(
                        position: (rect) => Offset(0, rect.bottom),
                        builder: (context, rect, rRect) {
                          return SizedBox(
                            width: MediaQuery.of(context).size.width,
                            child: Center(
                              child: Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: Text(
                                  'Current Counter will be displayed here',
                                  style: textTheme.bodyText2
                                      .copyWith(color: tutorialColor),
                                ),
                              ),
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                  child: Text(
                    '$_counter',
                    style: Theme.of(context).textTheme.headline4,
                  ),
                ),
              ],
            ),
          ),
          floatingActionButton: OverlayTutorialHole(
            enabled: true,
            overlayTutorialEntry: OverlayTutorialRectEntry(
              padding: const EdgeInsets.all(8.0),
              radius: const Radius.circular(16.0),
              overlayTutorialHints: <OverlayTutorialWidgetHint>[
                OverlayTutorialWidgetHint(
                  builder: (context, rect, rRect) {
                    print("I_AM_REBUILT");
                    return Positioned(
                      top: rRect.top - 24.0,
                      left: rRect.left,
                      child: Text(
                        'Try this out',
                        style:
                            textTheme.bodyText2.copyWith(color: tutorialColor),
                      ),
                    );
                  },
                ),
                OverlayTutorialWidgetHint(
                  position: (rect) => Offset(0, rect.center.dy),
                  builder: (context, rect, rRect) {
                    return SizedBox(
                      width: rRect.left,
                      child: Padding(
                        padding: const EdgeInsets.only(right: 8.0),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            Flexible(
                              child: Text(
                                'Click here to add counter',
                                style: textTheme.bodyText2
                                    .copyWith(color: tutorialColor),
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                ),
              ],
            ),
            child: FloatingActionButton(
              onPressed: _incrementCounter,
              tooltip: 'Increment',
              child: Icon(Icons.add),
            ),
          ), // This trailing comma makes auto-formatting nicer for build methods.
        ),
      ),
    );
  }
}
```

**Comment by TabooSun** [comment]
Hi @ilkercankaya, I am sorry to hear that this issue persists. However, please bear with this, currently, there is no way we can get around with this as far as I know. This is a Flutter issue where we are unable to listen to the position changes of a widget. Hence, I need to rebuild every time to ensure that the hole can be cropped correctly.

Is there any sample code that you can show me which makes this issue a deal-breaker for you? If it is unforgivable, I can try to escalate this issue to Flutter team to seek for help.

**Comment by ilkercankaya** [comment]
Hi @TabooSun, Thank you for the details. What I am trying to do is basically I have a queue of tutorials and I pop from these tutorials and display the corresponding tutorials hint in a `OverlayTutorialWidgetHint`. I do not pop tutorials inside the builder method but with gesture detectors such as swipe, onTap etc. However, the repeated builder calls sometimes makes my code throw because it somehow rebuilds even If I turn off the hint by switching it to a `SizedBox.shrink()`  and even if i safe guard it with code like `if (tutorialQueue.isNotEmpty) return SizedBox.shrink();` I get a strange bug where, When I navigate back to the screen where the tutorial overlay lies from another screen the builder draws the same hint several times rather than only once. I suspect this has something to do with the builders repeated calls. I would want to share my code but its too complicated and due to NDA's I cant give you the exact code.  

I do not know if my description was enough for you, I wanted to share.

**Comment by TabooSun** [comment]
Hi @ilkercankaya, I have been trying to picture your description. However, it turns out quite hard because there are many possibilities. Without any minimal reproducible code, I am unable to correctly pinpoint the issue.

Is it possible that you somehow provide your code? I am pretty sure that you can rewrite some of the logic in a sample project, like the queue you mentioned.
