### ISSUE TITLE
How to make the overlay disappear when the user clicks anywhere on the modal overlay?

### ISSUE THREAD

**Issue by MrCsabaToth** [TabooSun/overlay_tutorial#26]
Maybe I'm doing it wrong, but I'm testing the plugin and I leave a cutout for the button which makes it appear and that button make it disappear as well. However I'd like the overlay to disappear if the user clicks anywhere on the overlay. And I'd also like the cutout buttons to not function while the overlay is up.

**Comment by MrCsabaToth** [comment]
Hmmm, I've found https://github.com/TabooSun/overlay_tutorial/issues/18
I propose to add my requested use-case as a boolean switch, something like this fork https://github.com/Guang1234567/overlay_tutorial/commit/5c4460c4a570ed17885f1b1e4bca1de2d9340c44 (it uses IgnorePointer instead of AbsorbPointer).

**Comment by MrCsabaToth** [comment]
I wrapped the _OverlayTutorialBackbone into an AbsorbPointer (in my fork), so now the clicks won't go through. But I cannot find a click or tap event I'd be able to leverage to make the overlay disappear.

**Comment by MrCsabaToth** [comment]
https://stackoverflow.com/questions/68586256/how-to-display-a-dismissable-tutorial-overlay-in-my-flutter-app

**Comment by TabooSun** [comment]
Can I have a simple reproducible code that you want to achieve?

**Comment by TabooSun** [comment]
I am not sure if I am understanding it correctly. So you would just want the button to not clickable and remain the rest to be clickable so that you can allow dismiss, right? Can't you just disable the button only? 

If this is not the case, I would need some reproducible code to further understand it.

**Comment by MrCsabaToth** [comment]
> I am not sure if I am understanding it correctly. So you would just want the button to not clickable and remain the rest to be clickable so that you can allow dismiss, right? Can't you just disable the button only?
> 
> If this is not the case, I would need some reproducible code to further understand it.

I don't want anything to be clickable. I want the overlay to come up so the user can see what is what. Then when the user clicks anywhere the overlay would disappear, so the usage of the app can continue.

**Comment by TabooSun** [comment]
Still not sure if I am picturing it right.

```dart
// Value can be changed here to toggle the Overlay Tutorial.
final enabled = true;

return GestureDetector(
      onTap: () {
        print("Close overlay here.");
      },
      child: OverlayTutorialScope(
        enabled: enabled,
        child: AbsorbPointer(
          absorbing: enabled,
          child: Scaffold(
            appBar: AppBar(
              title: Text(widget.title),
            ),
            body: Center(
              child: OverlayTutorialHole(
                enabled: enabled,
                overlayTutorialEntry: OverlayTutorialRectEntry(
                  padding: const EdgeInsets.symmetric(horizontal: 8.0),
                  radius: const Radius.circular(16.0),
                ),
                child: OutlinedButton(
                  onPressed: () {
                    print('Inner button pressed');
                  },
                  child: Text('Inner button'),
                ),
              ),
            ),
          ),
        ),
      ),
    );
```

![image](https://user-images.githubusercontent.com/31196825/127706052-9ec8f4b3-8663-45e6-8ab6-52129b284eab.png)

**Comment by MrCsabaToth** [comment]
Thanks for the suggestion, I was thinking along that line. I tried this solution earlier, however since the GestureDetector is stationary, after I dismiss the overlay it still captures the taps. After dismissal I'd need the detector to pass through any gestures. I'm fiddling with this.
I also want to create something which can be a PR, because I hate to rely on my on forks (which unfortunately I do now for 6 of my 40 package dependencies).

**Comment by TabooSun** [comment]
Can't you just set null to the GestureDetector onTap property? In this case the tap should be able to pass through.

```dart
// Value can be changed here to toggle the Overlay Tutorial.
final enabled = true;

return GestureDetector(
      onTap: enabled ? () {
        print("Close overlay here.");
      } : null,
      child: OverlayTutorialScope(
        enabled: enabled,
        child: AbsorbPointer(
          absorbing: enabled,
          child: Scaffold(
            appBar: AppBar(
              title: Text(widget.title),
            ),
            body: Center(
              child: OverlayTutorialHole(
                enabled: enabled,
                overlayTutorialEntry: OverlayTutorialRectEntry(
                  padding: const EdgeInsets.symmetric(horizontal: 8.0),
                  radius: const Radius.circular(16.0),
                ),
                child: OutlinedButton(
                  onPressed: () {
                    print('Inner button pressed');
                  },
                  child: Text('Inner button'),
                ),
              ),
            ),
          ),
        ),
      ),
    );

```

**Comment by MrCsabaToth** [comment]
That's what I'll try soon.

**Comment by MrCsabaToth** [comment]
It could be implemented in user-land with a combination of AbsorbPointer and GestureDetector wrapping
