### ISSUE TITLE
Ignoring pointer in hole, but handling in the rest of overlay

### ISSUE THREAD

**Issue by yegor-pelykh** [TabooSun/overlay_tutorial#42]
Is it possible using your package to make the button in the hole clickable when the overlay is open, that is, the overlay passes mouse events, but in the rest of the overlay, an event is triggered on click (for example, to close this overlay in this handler)?

**Comment by TabooSun** [comment]
I can't help if you don't share your code.

AFAIK, I don't block any interaction unless you use any widget that does so yourself in your code.

**Comment by yegor-pelykh** [comment]
An example is your package example:
![Example](https://user-images.githubusercontent.com/21262076/196680934-6683432a-992c-48bd-bbbf-a2aebfbf5896.png)

This fab does not increase the counter when you click on it.
I need this button to work.

At the same time, clicking on the rest of the place (which is gray), the overlay does not close.
But I need to close and call some function. Like `onTap` from `GestureDetector`

**Comment by TabooSun** [comment]
If you are referring to my example, I do use [`AbsorbPointer`](https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html). If you want to make the FAB interactive, you must not wrap `Scaffold` with `AbsorbPointer`.

**Comment by yegor-pelykh** [comment]
Yes, the button started working after removing the `AbsorbPointer`.

But how to don't pass mouse events through the rest part (blue colored)?
And how to handle gesture on this rest part like `onTap` from `GestureDetector`?

**Comment by TabooSun** [comment]
It really depends on how your code is, `AbsorbPointer` basically prevents the widget it wraps from receiving pointer event and you should be able to use it for your purpose. This is technically not a issue of this package; you should consider asking this in StackOverflow instead. 

I'll close it for now, do re-open if you think this is an issue.
