### ISSUE TITLE
click event to show overlay

### ISSUE THREAD

**Issue by pishguy** [TabooSun/overlay_tutorial#8]
how can i set click event to show the overlay instead of showing by default?

**Comment by TabooSun** [comment]
I dont really get you, can you provide a sample code?

**Comment by pishguy** [comment]
@TabooSun i think by default when we running application we can see tutorials on screen. i want to for example after clicking on `FloatingActionButton` user can see tutorial

**Comment by TabooSun** [comment]
Your example was still not clear for me. I think you should be able to just run `showOverlayTutorial` in `initState` of your stateful widget's state. 

You can try to provide a working example so that I can assist you further.

**Comment by sohyuyuan** [comment]
`final OverlayTutorialController _controller = OverlayTutorialController();`
`_controller.showOverlayTutorial();`

You can use showOverlayTutorial() in your button.
